### ISSUE TITLE
Benchmark graphs should not render backfilled zero data

### ISSUE THREAD

**Issue by linusg** [boa-dev/boa-dev.github.io#167]
Instead of having sudden jumps where a new engine was added to the benchmarks I propose to start the line in the middle of the graph instead:

![image](https://github.com/user-attachments/assets/087af0e2-7c3b-48b8-a2f0-79625c120634)

There's two simple ways to do that:

- Change the source files in https://github.com/boa-dev/data/ from `[0, 0, 0, ..., N, ...]` to `[null, null, null, ..., N, ...]`
- Change `data.results[engine]` to `data.results[engine].map(value => value || null)` in https://github.com/boa-dev/boa-dev.github.io/blob/cd6f62ec08e37308403f28202bb31ba12edbed79/src/components/benchmarks/index.tsx#L107

If someone can tell me which is preferred I'm happy to make a PR for this :)

**Comment by jasonwilliams** [comment]
Thanks for looking at this, I would vote for changing the data rather than the map, because if someone adds a new engine, they would still need to add the 0s in anyway, so we may as well fix this at the source.

**Comment by jedel1043** [comment]
Actually, why don't we use an AoS instead of a SoA?
```javascript
[
    {
        "boa": 50,
        "sm-jitless": 7000,
        // ... more data
    },
    {
        // ... more data
    }
]
```
That should remove the zeroes problem altogether.

**Comment by linusg** [comment]
I assume the concern was file size bloat when including the key every time.

**Comment by jedel1043** [comment]
> I assume the concern was file size bloat when including the key every time.

Hmm true.

New proposal: inverting the arrays so that the last entry is first. Any zero entry is not inserted, which should give us the freedom of choosing our favourite sentinel value for missing entries.

**Comment by jasonwilliams** [comment]
> I assume the concern was file size bloat when including the key every time.

Correct, I did it that way so the key wasn't repeated every time. It's not ideal, but it was the most space efficient format I could think of at the time. I think for now just switching to `null` is fine until we can have a database or something better than a file.

I don't think inverting will work, once you get the data into the chart library it will expect the values to all be the same length from the beginning so they won't match up.

**Comment by jedel1043** [comment]
> I don't think inverting will work, once you get the data into the chart library it will expect the values to all be the same length from the beginning so they won't match up.

Yeah that's intended. From the JS side we would fill the missing values with nulls or zeroes, then reverse every array

**Comment by linusg** [comment]
That sounds quite complicated for what we're trying to achieve here. Is there an issue with backfilling nulls beyond whoever is adding new engines having to also add the backfill data? Conceptually the equal-length arrays seem like a clean solution to me.

**Comment by jedel1043** [comment]
> Is there an issue with backfilling nulls beyond whoever is adding new engines having to also add the backfill data?

It fills the files with superfluous data, which increases with every new engine we add and will eventually become unmanageable when we have to add 1k null entries for a new engine in the future.

**Comment by jasonwilliams** [comment]
I’ve spoke to @jedel1043 about this and we’re fine to use nulls as the data file is a temporary measure anyway, we will most certainly move to a more sustainable method of storage in the long term

**Comment by linusg** [comment]
This was done in https://github.com/boa-dev/data/commit/188159ea8a0c75fc66c1c1b69c96a914441e6b07, thanks!
