### ISSUE TITLE
Logo Colors are negative in Dark Mode.

### ISSUE THREAD

**Issue by electrolyte-orb** [boa-dev/boa-dev.github.io#68]
# Logo is blue instead of yellow
## Also the visited links are bit invisible.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/55880176/202752534-bf193c7e-5423-48b1-8e6a-331d5d6b0280.png">

**Comment by jedel1043** [comment]
Closing since the new webpage fixed this.
