### ISSUE TITLE
Reload doesn't work in development mode.

### ISSUE THREAD

**Issue by electrolyte-orb** [boa-dev/boa-dev.github.io#70]
Environment: Node 16.16.0, Windows 11 x64

BAD CODE: 
https://github.com/boa-dev/boa-dev.github.io/blob/e5e92fdce0afbd4ec96aa49b15781674913e6b86/package.json#L10

Instead, a library like [`concurrently`] should be accounted for.
https://www.npmjs.com/package/concurrently

**Comment by nekevss** [comment]
Closing this issue as we've migrated from eleventy to docusaurus
